### ISSUE TITLE
Provide compiled library to use in python

### ISSUE THREAD

**Issue by EmmanuelMess** [dbrgn/svg2polylines#22]
Provide compiled library to use in python

**Comment by dbrgn** [comment]
Hi. Since this was a side project of mine which isn't in active use anymore, I try not to increase the project scope (because I do not have unlimited time for maintenance of open source projects).

Therefore I'll decline this request. The library includes an example project that demonstrates how the library can be used from Python, but right now I don't want to package it myself. (There are a few Rust projects that simplify publishing of Python wheels though, so it would definitely be doable.)
